# Generated by Django 3.0.7 on 2020-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Clerk'), (2, 'Accountant'), (3, 'Personal Banker'), (4, 'TEAM Manager'), (5, 'Director')], default=1),
        ),
    ]
